### ISSUE TITLE
cell.py and board.py - Rows should be 'ABCDEFGHI' and not 'ABCDEFGHJ'

### ISSUE THREAD

**Issue by Pranoy1c** [roukaour/sudoku#1]
sudoku/cell.py - Rows should be 'ABCDEFGHI' and not 'ABCDEFGHJ'

Same with board.py sudoku format.

Alphabetically, I comes before J. So the last row should be "I" and not "J"

**Comment by roukaour** [comment]
Frequently "I" and "O" are left unused for labels like these, since they're confused with "1" and "0".

**Comment by Pranoy1c** [comment]
Oh ok, didn't know that! Thanks you letting me know!
